import { strict as assert } from 'node:assert';
import { createCartridge } from '../src/core/cartridge.mjs';
import { PPUMemoryBus } from '../src/core/ppubus.mjs';
import { PPU2C02 } from '../src/core/ppu.mjs';
import { TraceHub } from '../src/core/debug.mjs';
import { NESMachine } from '../src/core/machine.mjs';
import { snapshotSignature } from '../src/core/diagnostics.mjs';
import { makeINES,setPrg8k,setChr1k,setVector } from './romfactory.mjs';

let passed=0;const test=(name,fn)=>{fn();console.log(`PASS ${name}`);passed++;};
function mapper4({prg8k=8,chr1k=16,mirroring='vertical',traceHub=null,onIRQChange=null}={}){
  const r=makeINES({mapper:4,prgBanks:prg8k/2,chrBanks:chr1k/8,mirroring});
  for(let i=0;i<prg8k;i++)setPrg8k(r,i,i);
  for(let i=0;i<chr1k;i++)setChr1k(r,i,0x40+i);
  return {rom:r,cart:createCartridge(r.bytes,{traceHub,onIRQChange})};
}
function writeReg(c,index,value,mode=0){c.cpuWrite(0x8000,(mode&0xc0)|(index&7));c.cpuWrite(0x8001,value);}
function edge(c,start,low=8,source='test'){c.observePpuAddress(0x0000,start,source);c.observePpuAddress(0x1000,start+low,source);}


test('MMC3 accepts compact 16KiB diagnostic ROMs by mirroring both 8KiB banks',()=>{const r=makeINES({mapper:4,prgBanks:1,chrBanks:0});setPrg8k(r,0,0x11);setPrg8k(r,1,0x22);const c=createCartridge(r.bytes);assert.deepEqual(c.prgMap(),[0,1,0,1]);assert.equal(c.cpuRead(0x8000),0x11);assert.equal(c.cpuRead(0xa000),0x22);assert.equal(c.cpuRead(0xc000),0x11);assert.equal(c.cpuRead(0xe000),0x22);});

test('MMC3 PRG mode 0 maps R6,R7,second-last,last in 8KiB slots',()=>{const {cart:c}=mapper4();writeReg(c,6,3);writeReg(c,7,5);assert.deepEqual(c.prgMap(),[3,5,6,7]);assert.equal(c.cpuRead(0x8000),3);assert.equal(c.cpuRead(0xa000),5);assert.equal(c.cpuRead(0xc000),6);assert.equal(c.cpuRead(0xe000),7);});
test('MMC3 PRG mode 1 swaps R6 with fixed second-last slot',()=>{const {cart:c}=mapper4();writeReg(c,6,3);writeReg(c,7,5);c.cpuWrite(0x8000,0x46);assert.deepEqual(c.prgMap(),[6,5,3,7]);assert.equal(c.cpuRead(0x8000),6);assert.equal(c.cpuRead(0xc000),3);});
test('MMC3 CHR mode 0 uses two 2KiB banks then four 1KiB banks',()=>{const {cart:c}=mapper4({chr1k:32});writeReg(c,0,5);writeReg(c,1,9);writeReg(c,2,12);writeReg(c,3,13);writeReg(c,4,14);writeReg(c,5,15);assert.deepEqual(c.chrMap(),[4,5,8,9,12,13,14,15]);for(let slot=0;slot<8;slot++)assert.equal(c.ppuRead(slot*0x400),0x40+c.chrMap()[slot]);});
test('MMC3 CHR inversion swaps the 2KiB pair half with the four 1KiB banks',()=>{const {cart:c}=mapper4({chr1k:32});writeReg(c,0,4);writeReg(c,1,8);writeReg(c,2,12);writeReg(c,3,13);writeReg(c,4,14);writeReg(c,5,15);c.cpuWrite(0x8000,0x80);assert.deepEqual(c.chrMap(),[12,13,14,15,4,5,8,9]);});
test('MMC3 mirroring control is live and four-screen boards ignore it',()=>{let q=mapper4({mirroring:'vertical'}),b=new PPUMemoryBus({cartridge:q.cart});q.cart.cpuWrite(0xa000,1);assert.equal(q.cart.mirroring,'horizontal');b.write8(0x2000,0x11);assert.equal(b.read8(0x2400),0x11);q=mapper4({mirroring:'four-screen'});q.cart.cpuWrite(0xa000,1);assert.equal(q.cart.mirroring,'four-screen');});
test('MMC3 PRG RAM enable and write-protect bits gate $6000-$7FFF',()=>{const {cart:c}=mapper4();c.cpuWrite(0x6000,0x11);assert.equal(c.cpuRead(0x6000),0x11);c.cpuWrite(0xa001,0xc0);c.cpuWrite(0x6000,0x22);assert.equal(c.cpuRead(0x6000),0x11);c.cpuWrite(0xa001,0x00);assert.equal(c.cpuRead(0x6000),0);c.cpuWrite(0xa001,0x80);c.cpuWrite(0x6000,0x33);assert.equal(c.cpuRead(0x6000),0x33);});
test('MMC3 IRQ reload clocks latch first, then decrements to zero and asserts',()=>{let irq=false;const {cart:c}=mapper4({onIRQChange:v=>irq=v});c.cpuWrite(0xc000,2);c.cpuWrite(0xc001,0);c.cpuWrite(0xe001,0);edge(c,0);assert.equal(c.irqCounter,2);assert.equal(irq,false);edge(c,20);assert.equal(c.irqCounter,1);edge(c,40);assert.equal(c.irqCounter,0);assert.equal(irq,true);});
test('MMC3 A12 filter rejects a short low pulse without clocking IRQ counter',()=>{const {cart:c}=mapper4();c.cpuWrite(0xc000,3);c.cpuWrite(0xc001,0);c.observePpuAddress(0x0000,0,'short');c.observePpuAddress(0x1000,4,'short');assert.equal(c.irqCounter,0);assert.equal(c.a12QualifiedEdges,0);assert.equal(c.a12RejectedEdges,1);});
test('$E000 acknowledges/clears MMC3 IRQ and $E001 only re-enables future IRQs',()=>{let irq=false;const {cart:c}=mapper4({onIRQChange:v=>irq=v});c.cpuWrite(0xc000,0);c.cpuWrite(0xc001,0);c.cpuWrite(0xe001,0);edge(c,0);assert.equal(irq,true);c.cpuWrite(0xe000,0);assert.equal(irq,false);assert.equal(c.irqEnabled,false);c.cpuWrite(0xe001,0);assert.equal(irq,false);assert.equal(c.irqEnabled,true);});
test('$2006 second write exposes the committed PPU address to MMC3 A12',()=>{const {cart:c}=mapper4();const b=new PPUMemoryBus({cartridge:c}),p=new PPU2C02({bus:b});p.cpuWrite(0x2006,0x00);p.cpuWrite(0x2006,0x00);p.runCycles(8);p.cpuWrite(0x2006,0x10);p.cpuWrite(0x2006,0x00);assert.equal(c.a12QualifiedEdges,1);assert.equal(c.irqCounter,0);});
test('$2007 read/write post-increment exposes A12 transitions to MMC3',()=>{for(const kind of ['read','write']){const {cart:c}=mapper4();const b=new PPUMemoryBus({cartridge:c}),p=new PPU2C02({bus:b});p.cpuWrite(0x2006,0x0f);p.cpuWrite(0x2006,0xff);p.runCycles(8);if(kind==='read')p.cpuRead(0x2007);else p.cpuWrite(0x2007,0x55);assert.equal(p.v&0x3fff,0x1000);assert.equal(c.a12QualifiedEdges,1,kind);}});
test('PPU bus hides internal palette reads from mapper-visible A12 observer',()=>{const {cart:c}=mapper4();let cyc=0;const b=new PPUMemoryBus({cartridge:c});b.setCycleProvider(()=>cyc);b.read8(0x0000,'external-low');cyc=20;b.read8(0x3f10,'pixel-palette');assert.equal(c.a12QualifiedEdges,0);assert.equal(c.a12High,false);cyc=21;b.read8(0x1000,'external-high');assert.equal(c.a12QualifiedEdges,1);});
test('raw mapper A12 trace is opt-in while high-level IRQ clocks stay visible',()=>{const t=new TraceHub(),{cart:c}=mapper4({traceHub:t});c.cpuWrite(0xc000,1);c.cpuWrite(0xc001,0);edge(c,0);assert.equal(t.snapshot('mapperA12').length,0);assert.ok(t.snapshot('mapper').some(e=>e.type==='mmc3-irq-clock'));t.enable('mapperA12');edge(c,20);assert.ok(t.snapshot('mapperA12').some(e=>e.type==='a12-rise-qualified'));});
test('real PPU fetch schedule produces qualified MMC3 A12 edges without palette pollution',()=>{const t=new TraceHub();t.enable('mapperA12');const {cart:c}=mapper4({traceHub:t});const b=new PPUMemoryBus({cartridge:c,traceHub:t}),p=new PPU2C02({bus:b,traceHub:t});p.oam.fill(0xff);p.ctrl=0x08; // sprites $1000, background $0000
p.mask=0x18;p.scanline=261;p.dot=0;for(let i=0;i<341*3;i++)p.tick();const q=t.snapshot('mapperA12').filter(e=>e.type==='a12-rise-qualified');assert.ok(q.length>=2,'expected roughly one qualified edge per rendered scanline');assert.ok(q.some(e=>String(e.source).startsWith('sprite-pattern-dummy')));});
test('sprite-$1000 MMC3 A12 clock lands on the pattern fetch phase, not dot 257',()=>{const t=new TraceHub();t.enable('mapperA12');const {cart:c}=mapper4({traceHub:t});const b=new PPUMemoryBus({cartridge:c,traceHub:t}),p=new PPU2C02({bus:b,traceHub:t});p.oam.fill(0xff);p.ctrl=0x08;p.mask=0x18;p.scanline=261;p.dot=0;while(p.ppuCycle<=261)p.tick();const q=t.snapshot('mapperA12').filter(e=>e.type==='a12-rise-qualified');assert.ok(q.length>=1);assert.equal(q[0].ppuCycle,261);assert.equal(q[0].source,'sprite-pattern-dummy-lo');});
test('one rendered PPU frame clocks MMC3 A12 exactly 241 times in the common sprite-$1000 layout',()=>{const {cart:c}=mapper4();const b=new PPUMemoryBus({cartridge:c}),p=new PPU2C02({bus:b});p.oam.fill(0xff);p.ctrl=0x08;p.mask=0x18;p.scanline=261;p.dot=0;const start=c.a12QualifiedEdges;for(let i=0;i<341*262;i++)p.tick();assert.equal(c.a12QualifiedEdges-start,241);});
test('real PPU fetch schedule also clocks MMC3 when background uses $1000 and sprites use $0000',()=>{const t=new TraceHub();t.enable('mapperA12');const {cart:c}=mapper4({traceHub:t});const b=new PPUMemoryBus({cartridge:c,traceHub:t}),p=new PPU2C02({bus:b,traceHub:t});p.oam.fill(0xff);p.ctrl=0x10; // background $1000, sprites $0000
p.mask=0x18;p.scanline=261;p.dot=0;for(let i=0;i<341*3;i++)p.tick();const q=t.snapshot('mapperA12').filter(e=>e.type==='a12-rise-qualified');assert.ok(q.length>=2,'expected qualified edges after sprite fetch holds A12 low');assert.ok(q.some(e=>String(e.source).startsWith('bg-pattern')));});
test('MMC3 IRQ line is ORed with APU IRQ instead of one source clearing the other',()=>{const r=makeINES({mapper:4,prgBanks:4,chrBanks:1});for(let i=0;i<8;i++)setPrg8k(r,i,0xea);setVector(r,0xfffc,0xe000);setVector(r,0xfffe,0xe100);const m=new NESMachine();m.loadROM(r.bytes);m.setIRQSource('apu',true);m.setIRQSource('mapper',true);m.setIRQSource('apu',false);assert.equal(m.cpu.irqLine,true);m.setIRQSource('mapper',false);assert.equal(m.cpu.irqLine,false);});
test('synthetic Mapper4 ROM can raise A12 IRQ into the real CPU IRQ vector',()=>{const r=makeINES({mapper:4,prgBanks:4,chrBanks:1});for(let i=0;i<8;i++)setPrg8k(r,i,0xea);setVector(r,0xfffc,0xe000);setVector(r,0xfffe,0xe100);const m=new NESMachine();m.loadROM(r.bytes);m.cpu.setFlag(0x04,false);m.bus.write8(0xc000,0);m.bus.write8(0xc001,0);m.bus.write8(0xe001,0);edge(m.cartridge,0);assert.equal(m.cpu.irqLine,true);const spent=m.cpu.step();assert.equal(spent,7);assert.equal(m.cpu.pc,0xe100);m.bus.write8(0xe000,0);assert.equal(m.irqSources.mapper,false);});
test('MMC3 save state restores bank registers, A12 filter state and asserted IRQ',()=>{let line=false;const {cart:c}=mapper4({onIRQChange:v=>line=v});writeReg(c,6,3);c.cpuWrite(0xc000,0);c.cpuWrite(0xc001,0);c.cpuWrite(0xe001,0);c.observePpuAddress(0x0000,100,'save-low');const s=c.exportState(),sig=snapshotSignature(s);writeReg(c,6,1);c.observePpuAddress(0x1000,120,'mutate');c.cpuWrite(0xe000,0);c.importState(s);assert.equal(snapshotSignature(c.exportState()),sig);assert.equal(c.prgMap()[0],3);assert.equal(c.a12LowSince,100);assert.equal(line,false);});

console.log(`\n${passed}/21 P5.5 MMC3 tests passed`);
