import { strict as assert } from 'node:assert';
import { createCartridge } from '../src/core/cartridge.mjs';
import { PPUMemoryBus } from '../src/core/ppubus.mjs';
import { FLAG } from '../src/core/cpu6502.mjs';
import { CPU2A03, UNOFFICIAL_OPCODES, STABLE_UNOFFICIAL_OPCODE_COUNT } from '../src/core/cpu2a03.mjs';
import { FlatMemoryBus } from '../src/core/bus.mjs';
import { NESMachine } from '../src/core/machine.mjs';
import { snapshotSignature } from '../src/core/diagnostics.mjs';
import { hashAudio } from '../src/core/apu.mjs';
import { makeINES, setResetVector, setPrg, mmc1Write5 } from './romfactory.mjs';
let passed=0;const test=(name,fn)=>{fn();console.log(`PASS ${name}`);passed++;};

test('Mapper 2 UxROM switches $8000 bank and fixes last bank at $C000',()=>{const r=makeINES({mapper:2,prgBanks:4,chrBanks:0});const c=createCartridge(r.bytes);assert.equal(c.cpuRead(0x8000),0);assert.equal(c.cpuRead(0xc000),3);c.cpuWrite(0x8000,2);assert.equal(c.cpuRead(0x8000),2);assert.equal(c.cpuRead(0xc000),3);});
test('Mapper 2 state restores selected PRG bank',()=>{const c=createCartridge(makeINES({mapper:2,prgBanks:4,chrBanks:0}).bytes);c.cpuWrite(0x8000,2);const s=c.exportState();c.cpuWrite(0x8000,1);c.importState(s);assert.equal(c.cpuRead(0x8000),2);});
test('Mapper 3 CNROM switches 8KiB CHR banks without changing PRG',()=>{const c=createCartridge(makeINES({mapper:3,prgBanks:2,chrBanks:4}).bytes);assert.equal(c.ppuRead(0),0x40);c.cpuWrite(0x8000,2);assert.equal(c.ppuRead(0),0x44);assert.equal(c.ppuRead(0x1000),0x45);assert.equal(c.cpuRead(0x8000),0);});
test('MMC1 serial register selects PRG bank with fixed-last default mode',()=>{const c=createCartridge(makeINES({mapper:1,prgBanks:4,chrBanks:2}).bytes);assert.equal(c.cpuRead(0x8000),0);assert.equal(c.cpuRead(0xc000),3);mmc1Write5(c,0xe000,2);assert.equal(c.cpuRead(0x8000),2);assert.equal(c.cpuRead(0xc000),3);});
test('MMC1 reset write discards partial shift and restores fixed-last mode',()=>{const c=createCartridge(makeINES({mapper:1,prgBanks:4,chrBanks:2}).bytes);c.cpuWrite(0xe000,1);c.cpuWrite(0xe000,0);c.cpuWrite(0x8000,0x80);mmc1Write5(c,0xe000,1);assert.equal(c.prgBank,1);assert.equal((c.control>>2)&3,3);});
test('MMC1 supports fixed-first and 32KiB PRG modes',()=>{const c=createCartridge(makeINES({mapper:1,prgBanks:4,chrBanks:2}).bytes);mmc1Write5(c,0xe000,2);mmc1Write5(c,0x8000,0x0a);assert.equal(c.cpuRead(0x8000),0);assert.equal(c.cpuRead(0xc000),2);mmc1Write5(c,0x8000,0x02);assert.equal(c.cpuRead(0x8000),2);assert.equal(c.cpuRead(0xc000),3);});
test('MMC1 4KiB CHR mode independently selects both pattern-table halves',()=>{const c=createCartridge(makeINES({mapper:1,prgBanks:2,chrBanks:4}).bytes);mmc1Write5(c,0x8000,0x1c);mmc1Write5(c,0xa000,2);mmc1Write5(c,0xc000,5);assert.equal(c.ppuRead(0),0x42);assert.equal(c.ppuRead(0x1000),0x45);});
test('MMC1 mirroring changes are observed live by PPU bus',()=>{const c=createCartridge(makeINES({mapper:1,prgBanks:2,chrBanks:0}).bytes),b=new PPUMemoryBus({cartridge:c});mmc1Write5(c,0x8000,0x0e);b.write8(0x2000,0x11);b.write8(0x2400,0x22);assert.equal(b.read8(0x2800),0x11);assert.equal(b.read8(0x2c00),0x22);mmc1Write5(c,0x8000,0x0c);b.write8(0x2000,0x55);assert.equal(b.read8(0x2c00),0x55);mmc1Write5(c,0x8000,0x0d);b.write8(0x2400,0x66);assert.equal(b.read8(0x3000),0x66);});
test('Mapper trace exposes bank-switch commits on the global timeline',()=>{const events=[];const traceHub={emit(ch,e){events.push({ch,...e});}};const c=createCartridge(makeINES({mapper:1,prgBanks:4,chrBanks:2}).bytes,{traceHub});mmc1Write5(c,0xe000,2);assert.equal(events.filter(e=>e.type==='mmc1-shift').length,5);const commit=events.find(e=>e.type==='mmc1-commit');assert.equal(commit.register,'prg');assert.equal(commit.prgBank,2);});
test('Battery SRAM can be exported and imported only for battery carts',()=>{const a=createCartridge(makeINES({mapper:0,prgBanks:1,chrBanks:0,battery:true}).bytes),b=createCartridge(makeINES({mapper:0,prgBanks:1,chrBanks:0,battery:true}).bytes);a.cpuWrite(0x6000,0xde);a.cpuWrite(0x7fff,0xad);const save=a.exportBatteryRAM();b.importBatteryRAM(save);assert.equal(b.cpuRead(0x6000),0xde);assert.equal(b.cpuRead(0x7fff),0xad);const n=createCartridge(makeINES({mapper:0,prgBanks:1,chrBanks:0}).bytes);assert.equal(n.exportBatteryRAM(),null);});
test('Battery SRAM rejects wrong-sized persistence blobs',()=>{const c=createCartridge(makeINES({mapper:0,prgBanks:1,chrBanks:0,battery:true}).bytes);assert.throws(()=>c.importBatteryRAM(new Uint8Array(4)),/size mismatch/);});

test('Stable unofficial opcode table contains 86 implemented opcodes',()=>{assert.equal(STABLE_UNOFFICIAL_OPCODE_COUNT,86);assert.equal(UNOFFICIAL_OPCODES.filter(Boolean).length,86);});
function fx(code){const b=new FlatMemoryBus(),cpu=new CPU2A03(b);b.write8(0xfffc,0);b.write8(0xfffd,0x80);b.load(0x8000,Uint8Array.from(code));cpu.reset();return {b,cpu};}
test('LAX and SAX unofficial instructions combine load/store register semantics',()=>{const {b,cpu}=fx([0xa7,0x10,0x87,0x11]);b.write8(0x10,0xa5);cpu.step();assert.equal(cpu.a,0xa5);assert.equal(cpu.x,0xa5);cpu.step();assert.equal(b.read8(0x11),0xa5);});
test('SLO/RLA/SRE/RRA compose RMW with ALU and preserve carry behavior',()=>{let q=fx([0x07,0x10]);q.b.write8(0x10,0x81);q.cpu.a=1;q.cpu.step();assert.equal(q.b.read8(0x10),2);assert.equal(q.cpu.a,3);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0x27,0x10]);q.b.write8(0x10,0x80);q.cpu.a=0xff;q.cpu.setFlag(FLAG.C,true);q.cpu.step();assert.equal(q.b.read8(0x10),1);assert.equal(q.cpu.a,1);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0x47,0x10]);q.b.write8(0x10,3);q.cpu.a=0xff;q.cpu.step();assert.equal(q.b.read8(0x10),1);assert.equal(q.cpu.a,0xfe);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0x67,0x10]);q.b.write8(0x10,2);q.cpu.a=1;q.cpu.setFlag(FLAG.C,false);q.cpu.step();assert.equal(q.b.read8(0x10),1);assert.equal(q.cpu.a,2);});
test('DCP and ISC compose DEC/CMP and INC/SBC',()=>{let q=fx([0xc7,0x10]);q.b.write8(0x10,0x41);q.cpu.a=0x40;q.cpu.step();assert.equal(q.b.read8(0x10),0x40);assert.equal(q.cpu.getFlag(FLAG.Z),true);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0xe7,0x10]);q.b.write8(0x10,0x0f);q.cpu.a=0x20;q.cpu.setFlag(FLAG.C,true);q.cpu.step();assert.equal(q.b.read8(0x10),0x10);assert.equal(q.cpu.a,0x10);});
test('ANC/ALR/ARR/AXS/LAS stable unofficial semantics',()=>{let q=fx([0x0b,0xff]);q.cpu.a=0x80;q.cpu.step();assert.equal(q.cpu.a,0x80);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0x4b,0x03]);q.cpu.a=0x03;q.cpu.step();assert.equal(q.cpu.a,1);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0x6b,0xff]);q.cpu.a=0xff;q.cpu.setFlag(FLAG.C,false);q.cpu.step();assert.equal(q.cpu.a,0x7f);assert.equal(q.cpu.getFlag(FLAG.C),true);assert.equal(q.cpu.getFlag(FLAG.V),false);q=fx([0xcb,0x10]);q.cpu.a=0x3f;q.cpu.x=0x1f;q.cpu.step();assert.equal(q.cpu.x,0x0f);assert.equal(q.cpu.getFlag(FLAG.C),true);q=fx([0xbb,0x00,0x20]);q.b.write8(0x2000,0xf0);q.cpu.sp=0x7f;q.cpu.step();assert.equal(q.cpu.a,0x70);assert.equal(q.cpu.x,0x70);assert.equal(q.cpu.sp,0x70);});
test('Unofficial SBC $EB behaves like immediate SBC',()=>{const q=fx([0xeb,0x01]);q.cpu.a=5;q.cpu.setFlag(FLAG.C,true);assert.equal(q.cpu.step(),2);assert.equal(q.cpu.a,4);});
test('Memory-addressed unofficial NOP performs its target read',()=>{class Spy extends FlatMemoryBus{constructor(){super();this.hits=0;}read8(a,s){if((a&0xffff)===0x1234)this.hits++;return super.read8(a,s);}}const b=new Spy(),cpu=new CPU2A03(b);b.write8(0xfffc,0);b.write8(0xfffd,0x80);b.load(0x8000,Uint8Array.from([0x0c,0x34,0x12]));cpu.reset();cpu.step();assert.equal(b.hits,1);});
test('All implemented stable unofficial opcodes dispatch without unimplemented-mnemonic errors',()=>{for(let op=0;op<256;op++){if(!UNOFFICIAL_OPCODES[op])continue;const q=fx([op,0,0]);q.b.write8(0,0);q.b.write8(1,0x20);try{q.cpu.step();}catch(e){throw new Error(`$${op.toString(16).padStart(2,'0')}: ${e.message}`);}}});

test('Machine save state round-trips mutable CPU/PPU/APU/controller/bus state',()=>{const r=setResetVector(makeINES({mapper:0,prgBanks:1,chrBanks:0,battery:true}),0x8000);setPrg(r,0,0,Uint8Array.from([0x4c,0x00,0x80]));const m=new NESMachine();m.loadROM(r.bytes);m.bus.write8(0x12,0x99);m.ppu.oam[7]=0x55;m.ppuBus.palette[3]=0x2a;m.setController(1,0x81);m.apu.cpuWrite(0x4015,1);m.apu.cpuWrite(0x4000,0x1f);m.scheduler.advanceCycles(123,'test');const saved=m.saveState(),sig=snapshotSignature(saved);m.bus.write8(0x12,0);m.ppu.oam[7]=0;m.ppuBus.palette[3]=0;m.setController(1,0);m.scheduler.advanceCycles(77,'mutate');m.loadState(saved);assert.equal(snapshotSignature(m.saveState()),sig);assert.equal(m.bus.read8(0x12),0x99);assert.equal(m.ppu.oam[7],0x55);assert.equal(m.controllers.p1.buttons,0x81);});
test('Save state rejects a different ROM identity',()=>{const a=setResetVector(makeINES({mapper:0,prgBanks:1,chrBanks:0}),0x8000),b=setResetVector(makeINES({mapper:0,prgBanks:1,chrBanks:0}),0x8000);setPrg(a,0,0,Uint8Array.from([0xea]));setPrg(b,0,0,Uint8Array.from([0x4c,0,0x80]));const m1=new NESMachine(),m2=new NESMachine();m1.loadROM(a.bytes);m2.loadROM(b.bytes);assert.throws(()=>m2.loadState(m1.saveState()),/different ROM/);});
test('Save-state replay reproduces subsequent machine and audio state',()=>{const r=setResetVector(makeINES({mapper:0,prgBanks:1,chrBanks:0}),0x8000);setPrg(r,0,0,Uint8Array.from([0xea,0x4c,0x00,0x80]));const m=new NESMachine();m.loadROM(r.bytes);m.apu.cpuWrite(0x4015,1);m.apu.cpuWrite(0x4000,0x1f);m.apu.cpuWrite(0x4002,0x20);m.apu.cpuWrite(0x4003,0x08);m.step(50);m.drainAudio();const s=m.saveState();m.step(200);const sig1=snapshotSignature(m.saveState()),audio1=hashAudio(m.drainAudio());m.loadState(s);m.step(200);const sig2=snapshotSignature(m.saveState()),audio2=hashAudio(m.drainAudio());assert.equal(sig2,sig1);assert.equal(audio2,audio1);});

console.log(`\n${passed}/22 P5 tests passed`);
