import { runSelfTests } from '../tests/selftest.mjs';
import { NESMachine } from './core/machine.mjs';
import { BUTTON } from './core/controller.mjs';
import { hex8, hex16 } from './core/debug.mjs';
import { snapshotSignature } from './core/diagnostics.mjs';

const $=s=>document.querySelector(s),machine=new NESMachine();
const file=$('#rom'),status=$('#status'),meta=$('#meta'),tests=$('#tests'),trace=$('#trace');
const stepBtn=$('#step'),runBtn=$('#run'),frameBtn=$('#frame'),playBtn=$('#play'),resetBtn=$('#reset'),channel=$('#trace-channel');
const canvas=$('#screen'),ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
let playing=false,lastTs=0,frameAcc=0,audioCtx=null,audioCursor=0;
const FRAME_MS=1000/60.0988;
const keys=new Map([['KeyZ',BUTTON.A],['KeyX',BUTTON.B],['ShiftLeft',BUTTON.SELECT],['ShiftRight',BUTTON.SELECT],['Enter',BUTTON.START],['ArrowUp',BUTTON.UP],['ArrowDown',BUTTON.DOWN],['ArrowLeft',BUTTON.LEFT],['ArrowRight',BUTTON.RIGHT]]);let held=0;

function showReport(r){tests.innerHTML=r.results.map(x=>`<li class="${x.ok?'ok':'bad'}">${x.ok?'✓':'✗'} ${x.name}</li>`).join('');$('#test-summary').textContent=`${r.passed}/${r.total} P1 CPU self-tests passed`;$('#test-summary').className=r.failed?'badbox':'okbox';}
function buttons(on){for(const b of [stepBtn,runBtn,frameBtn,playBtn,resetBtn])b.disabled=!on;}
function renderScreen(){if(!machine.loaded)return;ctx.putImageData(new ImageData(machine.ppu.framebuffer,256,240),0,0);}
async function ensureAudio(){if(!audioCtx)audioCtx=new AudioContext({sampleRate:48000});if(audioCtx.state==='suspended')await audioCtx.resume();audioCursor=Math.max(audioCursor,audioCtx.currentTime+0.03);}
function pumpAudio(){if(!audioCtx||!machine.loaded)return;const samples=machine.drainAudio();if(!samples.length)return;const b=audioCtx.createBuffer(1,samples.length,48000);b.copyToChannel(samples,0);const src=audioCtx.createBufferSource();src.buffer=b;src.connect(audioCtx.destination);const start=Math.max(audioCtx.currentTime+0.02,audioCursor);src.start(start);audioCursor=start+b.duration;}
function compactTrace(e){if(!e)return'';const stamp=e.cpuCycle!=null?` C${e.cpuCycle}`:'';if(e.channel==='cpu')return e.type==='interrupt'?`${e.kind} PC=$${hex16(e.pc)} -> $${hex16(e.nextPC)} +${e.spent}`:`$${hex16(e.pc)} ${e.mnemonic.padEnd(3)} ${e.mode.padEnd(3)} A=${hex8(e.a)} X=${hex8(e.x)} Y=${hex8(e.y)} SP=${hex8(e.sp)} +${e.spent}`;if(e.channel==='cpuMem')return `#${e.seq??'-'}${stamp} ${e.kind.toUpperCase()} $${hex16(e.address)} -> ${e.device}[$${hex16(e.mappedAddress)}] = $${hex8(e.value)} (${e.source})`;if(e.channel==='ppuReg')return `#${e.seq}${stamp} ${e.kind.toUpperCase()} $${hex16(e.address)}=$${hex8(e.value)} F${e.frame} S${e.scanline} D${e.dot} v=$${hex16(e.v)} t=$${hex16(e.t)} x=${e.x} w=${Number(e.w)}`;if(e.channel==='ppuMem')return `#${e.seq}${stamp} ${e.kind.toUpperCase()} $${hex16(e.address)} ${e.device}=$${hex8(e.value)} (${e.source})`;if(e.channel==='ppuEvent')return `#${e.seq}${stamp} ${e.type} F${e.frame} S${e.scanline} D${e.dot}`;if(e.channel==='dma')return `#${e.seq}${stamp} ${e.type}${e.address!=null?` $${hex16(e.address)}`:''}${e.page!=null?` page=$${hex8(e.page)}`:''}${e.totalCycles?` cycles=${e.totalCycles}`:''}`;if(e.channel==='controller')return `#${e.seq}${stamp} ${e.type} P${e.port??'-'}${e.bit!=null?` bit=${e.bit}`:''}${e.mask!=null?` mask=$${hex8(e.mask)}`:''}`;if(e.channel==='apuReg')return `#${e.seq}${stamp} ${e.kind.toUpperCase()} $${hex16(e.address)}=$${hex8(e.value)}`;if(e.channel==='apuEvent')return `#${e.seq}${stamp} ${e.type}${e.frameCycle!=null?` frameCycle=${e.frameCycle}`:''}`;if(e.channel==='timeline')return `#${e.seq}${stamp} ${e.type}${e.owner?` owner=${e.owner}`:''}${e.stallCycles?` stall=${e.stallCycles}`:''}`;if(e.channel==='audioSample')return `#${e.seq}${stamp} sample=${Number(e.sample).toFixed(5)}`;return JSON.stringify(e);}
function showTrace(){if(!machine.loaded){trace.textContent='No trace yet.';return;}const c=channel.value;trace.textContent=machine.traceHub.tail(c,100).map(compactTrace).join('\n')||`No ${c} records yet.`;}
function showState(extra=''){const s=machine.snapshot();meta.textContent=JSON.stringify({signature:snapshotSignature(s),mapper:s.mapper,mirroring:s.mirroring,cpu:{pc:`$${hex16(s.cpu.pc)}`,cycles:s.cpu.cycles},clock:s.clock,ppu:{frame:s.ppu.frame,scanline:s.ppu.scanline,dot:s.ppu.dot,status:`$${hex8(s.ppu.status)}`},apu:s.apu,controller1:`$${hex8(s.controllers.p1.buttons)}`,breakReason:s.breakReason,note:'P4: controller + master clock + OAM/DMC DMA + 2A03 APU. DMA/APU cross-events have global cpuCycle/seq stamps.'},null,2)+(extra?`\n\n${extra}`:'');renderScreen();showTrace();}
function runAction(fn,label){try{const r=fn();pumpAudio();status.textContent=`${label}: ${r.executed??0} instructions, CPU ${r.cpuCycles??0} cycles (${r.stallCycles??0} stall); PPU F${machine.ppu.frame} S${machine.ppu.scanline} D${machine.ppu.dot}.`;status.className='okbox';showState();}catch(e){playing=false;playBtn.textContent='Play';status.textContent=e.message;status.className='badbox';showState();}}
async function togglePlay(){if(!machine.loaded)return;playing=!playing;playBtn.textContent=playing?'Pause':'Play';if(playing){await ensureAudio();lastTs=performance.now();frameAcc=0;requestAnimationFrame(loop);}}
function loop(ts){if(!playing)return;frameAcc+=Math.min(100,ts-lastTs);lastTs=ts;let ran=0;while(frameAcc>=FRAME_MS&&ran<3){machine.runFrame();frameAcc-=FRAME_MS;ran++;}if(ran){renderScreen();pumpAudio();showTrace();}requestAnimationFrame(loop);}
function updatePad(){if(machine.loaded)machine.setController(1,held);}
addEventListener('keydown',e=>{const b=keys.get(e.code);if(!b)return;e.preventDefault();held|=b;updatePad();});addEventListener('keyup',e=>{const b=keys.get(e.code);if(!b)return;e.preventDefault();held&=~b;updatePad();});

showReport(runSelfTests());buttons(false);showTrace();
file.addEventListener('change',async()=>{const f=file.files?.[0];if(!f)return;try{playing=false;playBtn.textContent='Play';held=0;const s=machine.loadROM(await f.arrayBuffer());status.textContent=`ROM 已接入 P4 整机：Mapper ${s.mapper}，CPU reset PC=$${hex16(s.cpu.pc)}。手柄、DMA、APU 已连接。`;status.className='okbox';buttons(true);showState(`ROM: ${f.name} (${f.size} bytes)`);}catch(e){status.textContent=e.message;status.className='badbox';buttons(false);meta.textContent='';trace.textContent='';ctx.clearRect(0,0,256,240);}});
stepBtn.addEventListener('click',()=>runAction(()=>machine.step(1),'Step'));runBtn.addEventListener('click',()=>runAction(()=>machine.step(1000),'Run 1000'));frameBtn.addEventListener('click',()=>runAction(()=>machine.runFrame(),'Run frame'));playBtn.addEventListener('click',togglePlay);resetBtn.addEventListener('click',()=>{playing=false;playBtn.textContent='Play';machine.reset();updatePad();status.textContent=`整机 reset：CPU PC=$${hex16(machine.cpu.pc)}`;status.className='okbox';showState();});channel.addEventListener('change',showTrace);
